Tshop/urls.py
from django.contrib import admin
from django.urls import path ,include
from Tshop import settings
from django.conf.urls.static import static  #for serving images in site

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls'))           #to add urls of STORE ,include is used and urls copy is made in store folder
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path
from store.views import home,cart,LoginView,OrderListView, signout,signup,add_to_cart,checkout ,contact_us
from store.views import validatePayment ,ProductDetailView
from django.contrib.auth.decorators import login_required 


urlpatterns = [
    path('',home,name='homepage'),   #here name is alias
    path('cart/',cart),     #to view cart page , 2nd cart is a function created in views.py in store folder 
    path('orders/',login_required(OrderListView.as_view(),login_url='/login'),name='orders'),
    path('login/',LoginView.as_view(), name='login'),
    path('signup/',signup),
    path('logout/',signout),
    path('checkout/',checkout),
    path('product/<str:slug>',ProductDetailView.as_view()),
    path('addtocart/<str:slug>/<str:size>',add_to_cart),
    path('validate_payment/',validatePayment),
    path('contactus/',contact_us),

    
   
]

store/models/cart.py
from django.db import models
from django.contrib.auth.models import User
from .tshirt import Tshirt 
from .size import SizeVariant

class Cart(models.Model):
    #tshirt required but its already in sizeVariant
    sizeVariant=models.ForeignKey(SizeVariant,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

store/models/order.py
from django.db import models
from django.contrib.auth.models import User
from .tshirt import Tshirt 
from .size import SizeVariant


class Order(models.Model):
    orderStatus = (
        ("PENDING","Pending"),        #this pending is shown before the payment            
        ("PLACED","placed"),
        ("CANCELLED","cancelled"),
        ("COMPLETED","Completed")
    )
    method = (                  
        ("ONLINE","Online"),
    )
    order_status=models.CharField(max_length=15,choices=orderStatus)
    payment_method=models.CharField(max_length=15,choices=method)
    shipping_address=models.CharField(max_length=100,null=False)
    phone=models.CharField(max_length=10,null=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    total=models.IntegerField(null=False)
    date=models.DateTimeField(null=False,auto_now_add=True)
    
class OrderItem(models.Model):
   order=models.ForeignKey(Order,on_delete=models.CASCADE)
   tshirt=models.ForeignKey(Tshirt,on_delete=models.CASCADE)
   size=models.ForeignKey(SizeVariant,on_delete=models.CASCADE)
   quantity=models.IntegerField(null=False)
   price=models.IntegerField(null=False)
   date=models.DateTimeField(null=False,auto_now_add=True)
 

store/models/size.py
from django.db import models
from django.contrib.auth.models import User
from store.models.tshirt import Tshirt   


class SizeVariant(models.Model):
    SIZES=(
        ("S","Small"),                    # S is for Database and Small is to show in admin site
        ("M","Medium"),
        ("L","Large"),
        ("XL","Extra Large"),
        ("XXL","Extra Extra Large")
    )
    price=models.IntegerField(null=False)      #price should not be NULL so false
    tshirt=models.ForeignKey(Tshirt,on_delete=models.CASCADE)
    size=models.CharField(choices=SIZES,max_length=5)   #choices will be shown as drop down list

    def __str__(self):
        return f'{self.size}'

store/forms/checkout_form.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django import forms
from django.contrib.auth.models import User    #importing model for form
from django.core.exceptions import ValidationError
from store.models import Order



class CheckForm(forms.ModelForm):
    class Meta:        #this means for wch model this form is used
        model = Order
        fields = ['shipping_address','phone','payment_method']   #only the specified attribute will be shown as form 

store/views/authentication.py
from django.shortcuts import render , HttpResponse, redirect
from store.forms.authforms import CustomerCreationForm,CustomerAuthForm   #this is from authforms.py file
from django.contrib.auth import authenticate, login as loginUser,logout  #used for login authentication 
                                                #the above authenticate,login and logout are predefined( existing by django)
from store.forms import CheckForm ,CustomerCreationForm, CustomerAuthForm
from store.models import Tshirt,SizeVariant, Cart , Order , OrderItem , Payment, Occasion,IdealFor,NeckType,Sleeve,Brand,Color
from django.views.generic.base import View

class LoginView(View):       #now LoginView is class
    print("LOGIN VIEW CLASS")
    def get(self,request):         #this will handle GET request
        form=CustomerAuthForm()
        next_page = request.GET.get('next')
        if next_page is not None:
            request.session['next_page'] = next_page
        return render(request,template_name="store/login.html",context={ 'form':form})

    def post(self,request): #this will handle POST request
        form=CustomerAuthForm(data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            if user:
                loginUser(request,user)  #if this is not given it shows anaonymous user

                session_cart = request.session.get('cart')   #to merge before login cart items to after login
                if session_cart is None:
                    session_cart=[]
                else:
                    for c in session_cart:
                        size=c.get('size')
                        tshirt_id=c.get('tshirt')
                        quantity=c.get('quantity')
                        cart_obj=Cart()           #creating new object for Cart Model
                        cart_obj.sizeVariant = SizeVariant.objects.get(size=size,tshirt =tshirt_id)
                        cart_obj.quantity = quantity
                        cart_obj.user=user
                        cart_obj.save()

                # { size , tshirt,quantity}
                cart = Cart.objects.filter(user=user)
                session_cart=[]
                for c in cart:
                    obj={
                        'size':c.sizeVariant.size,
                        'tshirt' : c.sizeVariant.tshirt.id,
                        'quantity': c.quantity
                    }
                    session_cart.append(obj)
                request.session['cart'] = session_cart
                next_page = request.session.get('next_page')
                if next_page is  None:
                    next_page='homepage'
                return redirect(next_page)
        else:
            return render(request,template_name="store/login.html",context={ 'form':form})
        
       

def signout(request): 
    logout(request)    #request.session.clear() this also can be written to clear session object of user when logged out
    return render(request,template_name="store/home.html")

def signup(request):
    if (request.method == 'GET'):        
        form=CustomerCreationForm()
        context={
            "form":form
        }
        return render(request,template_name="store/signup.html",context=context)
    else:
        form=CustomerCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            user.email = user.username
            user.first_name=user.first_name
            user.save()
            return redirect ('login')
            
        context={
            "form":form
        }
        return render(request,template_name="store/signup.html",context=context)

store/views/cart.py
from django.shortcuts import render , HttpResponse, redirect
from store.forms.authforms import CustomerCreationForm,CustomerAuthForm   #this is from authforms.py file
from django.contrib.auth.forms import AuthenticationForm  #for built in login form
from django.contrib.auth import authenticate, login as loginUser,logout  #used for login authentication 
                                                #the above authenticate,login and logout are predefined( existing by django)
from store.forms import CheckForm 
from store.models import Tshirt,SizeVariant, Cart , Order , OrderItem , Payment, Occasion,IdealFor,NeckType,Sleeve,Brand,Color
from math import floor
from django.contrib.auth.decorators import login_required 

def add_to_cart(request,slug,size):
    user=None
    if request.user.is_authenticated:
        user=request.user
    cart = request.session.get('cart')
    if cart is None:
        cart=[]
    
    tshirt=Tshirt.objects.get(slug=slug)
    add_cart_to_anom_user(cart,size,tshirt)     
           
    if user is not None:
        add_cart_to_database(user,size,tshirt)  
       
    request.session['cart'] = cart  #again inserting into session =cart is a list
    #print( slug, size)
    return_url=request.GET.get('return_url')  #to return to productdetail page again after clicking add to cart
    return redirect(return_url)  #redirecting to the same product page

def add_cart_to_database(user,size,tshirt):
    size=SizeVariant.objects.get(size=size,tshirt = tshirt)
    existing=Cart.objects.filter(user=user,sizeVariant=size)

    if len(existing) > 0:
        obj= existing[0]
        obj.quantity = obj.quantity + 1
        obj.save()        #saving for 
    else:
        c=Cart()           #creating an object for CART Table
        c.user=user           #insert into cart table values for user and below for sizevariant 
        c.sizeVariant=size
        c.quantity=1
        c.save()     #folr saving cart object


def add_cart_to_anom_user(cart,size,tshirt):
    flag = True  
    for cart_obj in cart:
        t_id=cart_obj.get('tshirt')   #will get tshirt id
        size_short=cart_obj.get('size')   #will get size of tshirt

        if t_id == tshirt.id and size == size_short:
            flag=False
            cart_obj['quantity'] = cart_obj['quantity']+1

    if flag:
        cart_obj={
            'tshirt':tshirt.id,
            'size':size,
            'quantity': 1
        }
        cart.append(cart_obj)

def cart(request):
    cart=request.session.get('cart')
    if cart is None:
        cart=[]
    
    for c in cart:
        tshirt_id=c.get('tshirt')        #getting id of tshirt added to cart
        tshirt=Tshirt.objects.get(id=tshirt_id)  #getting data from Tshirt Model
        c['tshirt']=tshirt   #tshirt in dictionary will be updated with tshirt name as a object
        c['size']=SizeVariant.objects.get(tshirt=tshirt_id,size=c['size'])

    print(cart)        
    return render(request , template_name='store/cart.html', context={'cart' : cart})    #to view cart page

store/views/checkout.py
from django.shortcuts import render , HttpResponse, redirect
from store.forms.authforms import CustomerCreationForm,CustomerAuthForm   #this is from authforms.py file
from django.contrib.auth.forms import AuthenticationForm  #for built in login form
from store.forms import CheckForm ,CustomerCreationForm, CustomerAuthForm
from django.contrib.auth import authenticate, login as loginUser,logout  #used for login authentication 
                                                #the above authenticate,login and logout are predefined( existing by django)
from store.models import Tshirt,SizeVariant, Cart , Order , OrderItem , Payment, Occasion,IdealFor,NeckType,Sleeve,Brand,Color
from math import floor
from django.contrib.auth.decorators import login_required 
from instamojo_wrapper import Instamojo
from Tshop.settings import API_KEY, AUTH_TOKEN

API = Instamojo(api_key=API_KEY, auth_token=AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/') #now in production Mode



       
#just for utility
def cal_total_payable_amount(cart):         #for adding total amount in cart page 
    total=0
    for c in cart:
        discount=c.get('tshirt').discount
        price=c.get('size').price
        sale_price=floor(price- (price*(discount/100)))
        total_of_single_product=sale_price *  c.get('quantity')
        total=total + total_of_single_product

    return total


@login_required(login_url='/login')   #it is a decorator
def checkout(request):
    if request.method == 'GET':     #for get Request
        form = CheckForm()
        cart=request.session.get('cart')
        if cart is None:
            cart=[]
        
        for c in cart:
            size_str = c.get('size')
            tshirt_id = c.get('tshirt')
            size_obj=SizeVariant.objects.get(size=size_str , tshirt=tshirt_id)   #now in cart list ,size is replaced by its object
            c['size']=size_obj
            c['tshirt']=size_obj.tshirt   #replacing in cart list , tshirt is id ,inplace of id tshirt object is stored

        return render(request,'store/checkout.html',{"form" : form, 'cart':cart})
    else:
        #this is for POST request
        form = CheckForm(request.POST)
        user = None
        if request.user.is_authenticated :
            user = request.user
        if form.is_valid():
            #payment should be done here
            cart=request.session.get('cart')
            if cart is None:
                cart = []
            for c in cart:
                size_str = c.get('size')
                tshirt_id = c.get('tshirt')
                size_obj=SizeVariant.objects.get(size=size_str , tshirt=tshirt_id)   #now in cart list ,size is replaced by its object
                c['size']=size_obj
                c['tshirt']=size_obj.tshirt
            shipping_address=form.cleaned_data.get('shipping_address')   #the shipping address entered will be stored in shipping_address variable
            phone=form.cleaned_data.get('phone')
            payment_method = form.cleaned_data.get('payment_method')
            total = cal_total_payable_amount(cart)
            print(shipping_address,phone,payment_method , total)
            order= Order()               #created Order Model object
            order.shipping_address = shipping_address   #entering data in ORDER table
            order.phone = phone
            order.payment_method= payment_method
            order.total = total
            order.order_status = "PENDING"
            order.user = user
            order.save()    
            #print(order.id)        # we will get order id 

            #saving to OrderItems Table
            for c in cart :
                order_item = OrderItem()   #creating new object for OrderItem Table
                order_item.order = order      #order id will be stored in order
                size=c.get('size')   #to access dictionary we use get('key')
                tshirt=c.get('tshirt')
                order_item.price = floor(size.price- (size.price*(tshirt.discount/100)))
                order_item.quantity = c.get('quantity')
                order_item.size = size
                order_item.tshirt = tshirt
                order_item.save()

            
            # CREATING PAYMENT
            # Create a new Payment Request
            response = API.payment_request_create(
                amount=order.total,
                purpose='Payment For Tshirts',
                buyer_name=f'{user.first_name} {user.last_name}',
                send_email=True,
                email=user.email,
                redirect_url="http://localhost:8000/validate_payment"
                )
            #print(response['payment_request'])
            payment_request_id = response['payment_request']['id']
            #the long URL of the payment request
            url =response['payment_request']['longurl']
            print(url)
            
            payment= Payment()
            payment.order= order
            payment.payment_request_id= payment_request_id
            payment.save()
            return redirect(url)
        else:
            return redirect('/checkout/')

store/views/contactus.py
from django.shortcuts import render , HttpResponse, redirect

#this is for contact us page
def contact_us(request):
    return render(request,template_name="store/contactus.html")

store/views/orders.py
from django.shortcuts import render , HttpResponse, redirect
from store.forms.authforms import CustomerCreationForm,CustomerAuthForm   #this is from authforms.py file
from django.contrib.auth.forms import AuthenticationForm  #for built in login form
from django.contrib.auth import authenticate, login as loginUser,logout  #used for login authentication 
                                                #the above authenticate,login and logout are predefined( existing by django)
from store.models import Tshirt,SizeVariant, Cart , Order , OrderItem , Payment, Occasion,IdealFor,NeckType,Sleeve,Brand,Color
from math import floor

from django.views.generic.list import ListView

# @login_required(login_url='/login') 


class OrderListView(ListView):
    template_name="store/orders.html"
    paginate_by=5
    model = Order
    
    context_object_name='orders'


    def get_queryset(self):
        print("GET QUERY SET")
        print()
        return Order.objects.filter(user = self.request.user).order_by('-date').exclude(order_status='PENDING') #we will get in descending order

store/templates/store/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>LogOff Online Shopping</title>

    <style>
        .display-5{
            font-size: 30px;
            font-weight: 300;
        }
        .display-8{
            font-size: 20px;
            font-weight: 300;
        }
        img.GeneratedImage {
            width:300px;
            height:225px;
            margin:10px;
            border-width:3px;
            border-color:#000033;
            border-style:groove;
}
    </style>
</head>

<body>
    <!---NAV BAR START--> 
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand font-italic" href="/"><strong>LOG OFF ONLINE STORE</strong></a>
        <img height="45px"  src="https://www.linkpicture.com/q/logoff.jpg"  alt="">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!ml is for margin left,we will get button right side>
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>


            </ul>
            <ul class="navbar-nav ml-auto">
                <!ml is for margin left,we will get button right side>
                    <li class="nav-item">
                        <a class="nav-link" href="/cart">Cart <span class="badge badge-info">{{request.session.cart|length}}</span> </<span></span></a>
                    </li>                   
                    {%if request.user.is_authenticated%}        <!if user is loggedin it should not show again login so this is used>
                    <li class="nav-item">
                        <a class="nav-link" href="/orders">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>                    
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/signup">Signup</a>
                    </li>
                    {% endif%}
                    <li class="nav-item">
                        <a class="nav-link text-success" href="/contactus">About Us </a>
                    </li> 
            </ul>

        </div>
    </nav>
    <!---NAV BAR END-->

    {% block content%}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

store/templates/store/cart.html
{% extends "./base.html" %}
{% load tshirt_tags %}   

{% block content%}

<div class="container">
    <div>
        <table class="table table-hover table-stripped">
            <thead>
                <tr>
                    <th># </th>
                    <th>Image</th>
                    <th>Tshirt </th>
                    <th>Size</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Sale Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
            </thead>

            <tbody>
                {% for c in cart%}

                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><img height="70px" class="img rounded-circle" src="{{c.tshirt.image.url}}" alt=""></td>
                        <td>{{c.tshirt.name}}</td>
                        <td>{{c.size.size}}</td>
                        <td>{{c.size.price|rupee}}</td>
                        <td>{{c.tshirt.discount}}%</td>
                        <td>{%clc_sale_price c.size.price c.tshirt.discount as sale_price %}{{sale_price|rupee}}</td>
                        <td>{{c.quantity}}</td>
                        <td>{% multiply c.quantity sale_price as total%}{{total|rupee}}</td>
                    </tr>


                {% endfor %}

                <tfoot>
                    <tr>
                        <th colspan="3"></th>
                        <th colspan="5">Payable Amount</th>
                        <th>{{cart |cal_total_payable_amount | rupee}}</th>
                    </tr>
                    <tr>
                        <th colspan="7"></th>
                        <th colspan="2"><a href="/checkout " class="btn btn-outline-dark">Continue To Checkout</a></th>
                    </tr>
                </tfoot>

            </tbody>

        </table>
    </div>


</div>

{% endblock %}

store/templates/store/checkout.html
{% extends "./base.html" %}
{% load crispy_forms_tags %} <! crispy form for bootstrap effect >
{% load tshirt_tags %} 


{% block content%}
<div class="container">
    <div class="p-2">
        <div class="display-5">Checkout Page</div>
        <hr>
        <div class="row">
            <div class="col-lg-5 border rounded p-3">  <! p3 is for padding>
                <form action="/checkout/" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <hr>
                    <div class ="form-group">
                        <input type="submit" value="checkout"  class="btn btn-outline-dark">
    
                    </div>
                </form>
    
            </div>

            <div class = 'col '>
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tshirt</th>
                            <th>Size</th>
                            <th>Price After Dis.</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in cart %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{c.size.tshirt.name}}</td>  <! in cart list  size is an object  and in that tshirt and in tshirt we get name>
                                <td>{{c.size.size}}</td>
                                <td>{% clc_sale_price  c.size.price c.size.tshirt.discount as result %} {{result |rupee}}</td>

                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                
                <hr>
                <div>
                    <div class="display-5 alert">Total Payable Amount :{{cart | cal_total_payable_amount | rupee}}</div>
                </div>

            </div>
        </div>

    </div>
</div>         

{% endblock %}

store/templates/store/orders.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% load orders_tags %}

{% block content%}
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Items</th>
                    <th>Status</th>
                    <th>Grand Total</th>
                </tr>
            </thead>
            
            <tbody>
                {% for order in orders %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{order.date|date}}</td>
                    
                    <td>
                        <table class="table table-sm">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Image</th>
                                    <th>Tshirt</th>
                                    <th>Price</th>
                                    <th>quantity</th>
                                    <th>Total</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for oi in order.orderitem_set.all%}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td><img height="60px" class="border" src="{{oi.tshirt.image.url}}" alt=""></td>
                                        <td>{{oi.tshirt.name}}</td>
                                        <td>{{oi.price|rupee}}</td>
                                        <td>{{oi.quantity}}</td>
                                        <td>{% multiply oi.quantity oi.price as result %} {{result|rupee}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>

                        </table>
                        <td>
                            <span class="badge badge-{% get_order_status_class order.order_status %}">{{order.order_status}}</span>
                        </td>
                        <td>{{order.total | rupee }}</td>
                    </td>
                </tr>


                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation " class="mt-2">
            <ul class="pagination justify-content-end">
              {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
              {% endif %}
              <li class="page-item">
                <a class="page-link" href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
              </li>

              {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
              {% endif %}
            </ul>
          </nav>

    </div>
          

{% endblock %}

store/templates/store/payment_failed.html
{% extends "./base.html" %}

{% block content%}
    <br>
    <br>
    <div class="jumbotron container p-2 alert alert-danger text-center">
        <h1 class="display-4">Payment Failed</h1>
        <p class="lead">Please try Again...</p>
        <hr class="my-4">
        <p>Your Payment Failed</p>
    </div>

{% endblock %}

store/templates/store/product_details.html
{% extends "./base.html" %}
{% load tshirt_tags %}

{% block content%}
<div class="container">
    <div class="row">
        <div class="col ">
            <div class="p-4 m-3">
                <div class="w-70 text-center mx-auto">
                    <img src="{{tshirt.image.url}}" class="img-fluid"  width="400" height="500"alt="">
                </div>
            </div>
        </div>
        <div class="col p-3 m-2">
            <br>
            <br>
            <br>
            <div >
                <div class="display-4">{{tshirt.name}}</div>
                <hr>
                <p>{{tshirt.description}}</p>               
            </div>

            <div class="row">
                <div class="col">
                    <label for="">Select Size</label>

                    <div class="row">    <! for sizes>
                        {% for size in tshirt.sizevariant_set.all %}
                            <div class="col-4 mt-2">
                                <a href="/product/{{tshirt.slug}}?size={{size.size}}" 
                                class="btn border btn-block btn-{% get_active_size_button_class active_size size %}">
                                    {{size.size}}
                                </a>
                            </div>
                        {% endfor%}
                    <br>
                    <br>
                    <div class="display-5 badge badge-info mt-2">
                        Save {{tshirt.discount}}%
                    </div>
                    </div>

                               
                </div>
                <div class="col   rounded border mt-3">
                    <div class="p-2">
                        <div class="p-3 display-8">
                            <span class="text-danger"><del>{{price|rupee}}</del></span>  <! see in views.py show_product function>
                            &nbsp;
                            <span>{{sell_price|rupee}}</span>                            
                        </div>
                        <a href="/addtocart/{{tshirt.slug}}/{{active_size.size}}?return_url={{request.get_full_path}}" class="btn btn-outline-dark btn-block">Add To Cart</a>
                        

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}